FROM node:12
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
#COPY package.json /usr/src/app/
#RUN npm install
#COPY . /usr/src/app
#COPY ./external_libraries/gsap /usr/src/app/node_modules/
RUN npm install -g @angular/cli@10
#EXPOSE 3000
