version: "2"
services:
  appClientBuildTekusV1:
    container_name: cont_client_build_tekus_v1
#build: ./client
    build:
      context: .
      dockerfile: Dockerfile-build-client
    image: image_client_build_tekus_v1
    volumes:
      - ./:/usr/src/app
    tty: true
#    command: >
#        bash -c "ng build --prod=true --aot=true --build--optimizer=true"
#        bash -c "ng build --prod=true"
#        bash -c "ng build --configuration="production"" 
