version: "2"
services:
  appClientBuildTekusV1:
    container_name: cont_client_build_tekus_v1
    build:
      context: .
      dockerfile: Dockerfile-build-client
    image: image_client_build_tekus_v1
    volumes:
      - ./:/usr/src/app
    tty: true