version: "2"
services:
  appPatatasAirMeasurementServerDevV1:
    container_name: cont_patatas_air_measurement_server_dev_v1
    build:
      context: .
      dockerfile: Dockerfile-dev-server
    image: image_patatas_air_measurement_server_dev_v1
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    tty: true
    networks:
      - app-network
    command: >
        bash -c "npm run build && npm run serve"
  appPatatasAirMeasurementClientDevV1:
    container_name: cont_patatas_air_measurement_client_dev_v1
    build:
      context: ./
      dockerfile: Dockerfile-build-client
    image: image_patatas_air_measurement_client_dev_v1
    ports:
      - "4200:4200"
    volumes:
      - ./client/:/usr/src/app
    tty: true
    networks:
      - app-network
    command: >
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
networks:
  app-network:
    driver: bridge
volumes:
  node_modules:

